ALM1Bank/Models/ErrorViewModel.cs
using System;

namespace ALM1Bank.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ALM1Bank/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ALM1Bank.Models;
using ALM1Bank.Data;

namespace ALM1Bank.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            var bankRepo = new BankRepository();

            return View(bankRepo);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ALM1Bank/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ALM1Bank.Data;
using Microsoft.AspNetCore.Mvc;

namespace ALM1Bank.Controllers
{
    public class TransactionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Withdraw(decimal amount, int accountID)
        {
            var repo = new BankRepository();
            var account = repo.Withdraw(amount, accountID);

            if (account)
            {
                return View("~/Views/Home/Index.cshtml", repo);
            }
            ViewBag.Message = "Något blev fel. Vänligen försök igen.";
            return View("Index");
        }

        public IActionResult Deposit(decimal amount, int accountID)
        {
            var repo = new BankRepository();
            var account = repo.Deposit(amount, accountID);

            if (account)
            {
                return View("~/Views/Home/Index.cshtml", repo);
            }

            ViewBag.Message = "Något blev fel. Vänligen försök igen.";
            return View("Index");
        }
    }
}

ALM1Bank/Controllers/TransferController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ALM1Bank.Data;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace ALM1Bank.Controllers
{
    public class TransferController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }



        public IActionResult Transfer(decimal amount, int accountIDOne,int accountIDTwo)
        {
            var repo = new BankRepository();
            var account = repo.Transfer(amount, accountIDOne, accountIDTwo);

            if (account)
            {
                return View("~/Views/Home/Index.cshtml", repo);
            }
            ViewBag.Message = "Något blev fel. Du har antingen försökt överföra ett för stort belopp, försökt skriva andra tecken än siffror eller skrivit in ett kontonr som inte existerar.";
            return View("Index");
        }

    

    }
}

ALM1Bank/Views/Home/Index.cshtml
@model ALM1Bank.Data.BankRepository

<h1>TJENA! Kolla våra kunder:</h1>

@foreach (var cust in Model.Customers)
{
    var balance = Model.Accounts.SingleOrDefault(x => x.AccountID == cust.AccountID).Balance;
    <h2>KundID: @cust.CustomerID - Namn: @cust.Name - Kontonummer: @cust.AccountID - Saldo: @balance pengar</h2>
    <hr />
}

ALM1Bank/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sebankian Sagrelius</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sebankian Sagrelius</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transaction" asp-action="Index">Insättning/Uttag</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transfer" asp-action="Index">ÖVerföring</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ALM1Bank - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

ALM1Bank/Views/Transaction/Index.cshtml
@model ALM1Bank.Data.BankRepository


<h1>Uttag/Insättning</h1>

<h2 style="color: red;">@ViewBag.Message</h2>

<form asp-action="Withdraw" asp-controller="Transaction" method="post">
    <h3>Uttag</h3>
    <label>Ange kontonummer:</label>
    <br />
    <input type="number" name="accountID" value="" />
    <br />
    <label>Ange belopp:</label>
    <br />
    <input type="number" name="amount" value="" />
    <br />
    <input type="submit" name="Bekräfta" value="Bekräfta" />
</form>

<br />
<hr />
<br />

<form asp-action="Deposit" asp-controller="Transaction" method="post">
    <h3>Insättning</h3>
    <label>Ange kontonummer:</label>
    <br />
    <input type="number" name="accountID" value="" />
    <br />
    <label>Ange belopp:</label>
    <br />
    <input type="number" name="amount" value="" />
    <br />
    <input type="submit" name="Bekräfta" value="Bekräfta" />
    <br />
</form>

ALM1Bank/Views/Transfer/Index.cshtml
@model ALM1Bank.Data.BankRepository

    <h2 style="color: red;">@ViewBag.Message</h2>
<div style="border: solid blue 5px; text-align:center; color: white; background-color: darkblue; border-radius:25%; margin-left: 10%; margin-top: 10%; ">
    <h2>Överföring</h2>
    <form asp-action="transfer" asp-controller="Transfer" method="post">

        <label>Från kontonummer:</label>
        <br />
        <input type="text" name="accountIDOne" value="" />
        <br />
        <label>Till kontonummer:</label>
        <br />
        <input type="text" name="accountIDTwo" value="" />
        <br />
        <label>Ange belopp:</label>
        <br />
        <input type="text" name="amount" value="" />
        <br />
        <input type="submit" name="Bekräfta" value="Bekräfta" />
        <br />
      
    </form>
</div>